logging:
  level:
    org.springframework.security.oauth2: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://msvc-auth-production.up.railway.app
      client:
        registration:
          msvc-users-client:
            provider: spring
            client-id: users-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: https://msvc-users-production.up.railway.app/users/authorized
            scope: read
            client-name: msvc-users-client
        provider:
          spring:
            issuer-uri: https://msvc-auth-production.up.railway.app